version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    # # dev
    # command: python manage.py runserver 0.0.0.0:8000
    # # prod
    command: gunicorn async_dydb.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"





